11:44 bilby INFO    : Loaded 157 posteriors
11:44 bilby INFO    : Using parabola_m2min_allgammazeta from variable_qmin.
11:44 bilby INFO    : Using PowerLawRedshift from gwpopulation.models.redshift.
11:44 bilby INFO    : Created gwpopulation.models.redshift.PowerLawRedshift with arguments {'z_max': 1.9}
11:44 bilby INFO    : Using parabola_m2min_allgammazeta from variable_qmin.
11:44 bilby INFO    : Using PowerLawRedshift from gwpopulation.models.redshift.
11:44 bilby INFO    : Created gwpopulation.models.redshift.PowerLawRedshift with arguments {'z_max': 1.9}
11:44 bilby INFO    : Loading VT data from O4a_parabolam2min_prod_allgammazeta_no190814_jax/data/injections.pkl.
11:44 bilby INFO    : Identified keys: mmin, gamma, mmax, sigpp, alpha, lam, gaussian_mass_maximum, mpp, zeta, beta, lamb
2024-06-06 11:44:35.183050: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:429] There was an error before creating cudnn handle (35): cudaErrorInsufficientDriver : CUDA driver version is insufficient for CUDA runtime version
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/local/condor/execute/dir_1198077/gwpopulation_pipe_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/gwpopulation_pipe/data_analysis.py", line 461, in main
    likelihood = create_likelihood(args, posteriors, model, selection)
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/gwpopulation_pipe/data_analysis.py", line 222, in create_likelihood
    likelihood = likelihood_class(
  File "/home/storm.colloms/.local/lib/python3.10/site-packages/gwpopulation/hyperpe.py", line 80, in __init__
    self.data = self.resample_posteriors(posteriors, max_samples=max_samples)
  File "/home/storm.colloms/.local/lib/python3.10/site-packages/gwpopulation/hyperpe.py", line 293, in resample_posteriors
    data[key] = xp.array(data[key])
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 2592, in array
    out_array: Array = lax_internal._convert_element_type(
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 559, in _convert_element_type
    return convert_element_type_p.bind(operand, new_dtype=new_dtype,
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/core.py", line 387, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/core.py", line 391, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/core.py", line 879, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/dispatch.py", line 86, in apply_primitive
    outs = fun(*args)
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
11:54 bilby INFO    : Loaded 157 posteriors
11:54 bilby INFO    : Using parabola_m2min_allgammazeta from variable_qmin.
11:54 bilby INFO    : Using PowerLawRedshift from gwpopulation.models.redshift.
11:54 bilby INFO    : Created gwpopulation.models.redshift.PowerLawRedshift with arguments {'z_max': 1.9}
11:54 bilby INFO    : Using parabola_m2min_allgammazeta from variable_qmin.
11:54 bilby INFO    : Using PowerLawRedshift from gwpopulation.models.redshift.
11:54 bilby INFO    : Created gwpopulation.models.redshift.PowerLawRedshift with arguments {'z_max': 1.9}
11:54 bilby INFO    : Loading VT data from O4a_parabolam2min_prod_allgammazeta_no190814_jax/data/injections.pkl.
11:54 bilby INFO    : Identified keys: sigpp, mmax, lam, mmin, mpp, gamma, beta, gaussian_mass_maximum, zeta, alpha, lamb
2024-06-06 11:54:53.507630: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:429] There was an error before creating cudnn handle (35): cudaErrorInsufficientDriver : CUDA driver version is insufficient for CUDA runtime version
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/local/condor/execute/dir_1198177/gwpopulation_pipe_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/gwpopulation_pipe/data_analysis.py", line 461, in main
    likelihood = create_likelihood(args, posteriors, model, selection)
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/gwpopulation_pipe/data_analysis.py", line 222, in create_likelihood
    likelihood = likelihood_class(
  File "/home/storm.colloms/.local/lib/python3.10/site-packages/gwpopulation/hyperpe.py", line 80, in __init__
    self.data = self.resample_posteriors(posteriors, max_samples=max_samples)
  File "/home/storm.colloms/.local/lib/python3.10/site-packages/gwpopulation/hyperpe.py", line 293, in resample_posteriors
    data[key] = xp.array(data[key])
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 2592, in array
    out_array: Array = lax_internal._convert_element_type(
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 559, in _convert_element_type
    return convert_element_type_p.bind(operand, new_dtype=new_dtype,
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/core.py", line 387, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/core.py", line 391, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/core.py", line 879, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/dispatch.py", line 86, in apply_primitive
    outs = fun(*args)
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
12:02 bilby INFO    : Loaded 157 posteriors
12:02 bilby INFO    : Using parabola_m2min_allgammazeta from variable_qmin.
12:02 bilby INFO    : Using PowerLawRedshift from gwpopulation.models.redshift.
12:02 bilby INFO    : Created gwpopulation.models.redshift.PowerLawRedshift with arguments {'z_max': 1.9}
12:02 bilby INFO    : Using parabola_m2min_allgammazeta from variable_qmin.
12:02 bilby INFO    : Using PowerLawRedshift from gwpopulation.models.redshift.
12:02 bilby INFO    : Created gwpopulation.models.redshift.PowerLawRedshift with arguments {'z_max': 1.9}
12:02 bilby INFO    : Loading VT data from O4a_parabolam2min_prod_allgammazeta_no190814_jax/data/injections.pkl.
12:02 bilby INFO    : Identified keys: beta, gaussian_mass_maximum, mpp, mmax, mmin, alpha, gamma, sigpp, lam, zeta, lamb
2024-06-06 12:02:02.298881: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:429] There was an error before creating cudnn handle (35): cudaErrorInsufficientDriver : CUDA driver version is insufficient for CUDA runtime version
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/local/condor/execute/dir_1198283/gwpopulation_pipe_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/gwpopulation_pipe/data_analysis.py", line 461, in main
    likelihood = create_likelihood(args, posteriors, model, selection)
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/gwpopulation_pipe/data_analysis.py", line 222, in create_likelihood
    likelihood = likelihood_class(
  File "/home/storm.colloms/.local/lib/python3.10/site-packages/gwpopulation/hyperpe.py", line 80, in __init__
    self.data = self.resample_posteriors(posteriors, max_samples=max_samples)
  File "/home/storm.colloms/.local/lib/python3.10/site-packages/gwpopulation/hyperpe.py", line 293, in resample_posteriors
    data[key] = xp.array(data[key])
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 2592, in array
    out_array: Array = lax_internal._convert_element_type(
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 559, in _convert_element_type
    return convert_element_type_p.bind(operand, new_dtype=new_dtype,
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/core.py", line 387, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/core.py", line 391, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/core.py", line 879, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/dispatch.py", line 86, in apply_primitive
    outs = fun(*args)
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
12:09 bilby INFO    : Loaded 157 posteriors
12:09 bilby INFO    : Using parabola_m2min_allgammazeta from variable_qmin.
12:09 bilby INFO    : Using PowerLawRedshift from gwpopulation.models.redshift.
12:09 bilby INFO    : Created gwpopulation.models.redshift.PowerLawRedshift with arguments {'z_max': 1.9}
12:09 bilby INFO    : Using parabola_m2min_allgammazeta from variable_qmin.
12:09 bilby INFO    : Using PowerLawRedshift from gwpopulation.models.redshift.
12:09 bilby INFO    : Created gwpopulation.models.redshift.PowerLawRedshift with arguments {'z_max': 1.9}
12:09 bilby INFO    : Loading VT data from O4a_parabolam2min_prod_allgammazeta_no190814_jax/data/injections.pkl.
12:09 bilby INFO    : Identified keys: sigpp, mpp, gamma, gaussian_mass_maximum, mmax, lam, beta, alpha, zeta, mmin, lamb
2024-06-06 12:09:43.579476: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:429] There was an error before creating cudnn handle (35): cudaErrorInsufficientDriver : CUDA driver version is insufficient for CUDA runtime version
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/local/condor/execute/dir_1199919/gwpopulation_pipe_analysis", line 8, in <module>
    sys.exit(main())
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/gwpopulation_pipe/data_analysis.py", line 461, in main
    likelihood = create_likelihood(args, posteriors, model, selection)
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/gwpopulation_pipe/data_analysis.py", line 222, in create_likelihood
    likelihood = likelihood_class(
  File "/home/storm.colloms/.local/lib/python3.10/site-packages/gwpopulation/hyperpe.py", line 80, in __init__
    self.data = self.resample_posteriors(posteriors, max_samples=max_samples)
  File "/home/storm.colloms/.local/lib/python3.10/site-packages/gwpopulation/hyperpe.py", line 293, in resample_posteriors
    data[key] = xp.array(data[key])
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 2592, in array
    out_array: Array = lax_internal._convert_element_type(
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 559, in _convert_element_type
    return convert_element_type_p.bind(operand, new_dtype=new_dtype,
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/core.py", line 387, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/core.py", line 391, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/core.py", line 879, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/storm.colloms/.conda/envs/O4apop-jax/lib/python3.10/site-packages/jax/_src/dispatch.py", line 86, in apply_primitive
    outs = fun(*args)
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
